# Generated by Django 4.2.1 on 2023-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grp',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
